### PR TITLE
Add ability to register & use custom writers

### PR DESCRIPTION
**Pull request by ronan-gloo**
Check the readme for explanations about how to use it.

### CODE REVIEW

**Review by benoit-apk — APPROVED** [review]
Would it be sound to add a `getWriter()` getter to `ProductGenerator`? (otherwise, we can carry on with using `static` properties on our writer class)

In any case, this is exactly what we needed, thanks!

**Comment by ronan-gloo** [comment]
getWriter() is supposed to return the currently used alias ?

**Comment by benoit-apk** [comment]
Forgot that `setWriter()` takes an alias and not a writer instance.. What about something like `getWriterInstance()` then, would it make sense?

**Comment by ronan-gloo** [comment]
Writers are only instantiated during the `write()` call. So requesting getWriterInstance will provides a different instance of the writer class used to process data

**Comment by benoit-apk** [comment]
Ok, so everything looks fine to me!

**Pull request merged**
